# Generated by Django 3.2.8 on 2024-05-15 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
