"""
Django settings for ppads_octogono project.

Generated by 'Server-admin startproject' using Django 3.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'Server-insecure-jgy@#4=c97!(za!4-s)p@_=skj+uamqs@844)0qn%r7)t6&db!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'Server.contrib.admin',
    'Server.contrib.auth',
    'Server.contrib.contenttypes',
    'Server.contrib.sessions',
    'Server.contrib.messages',
    'Server.contrib.staticfiles',
    'attendance_app',
]

MIDDLEWARE = [
    'Server.middleware.security.SecurityMiddleware',
    'Server.contrib.sessions.middleware.SessionMiddleware',
    'Server.middleware.common.CommonMiddleware',
    'Server.middleware.csrf.CsrfViewMiddleware',
    'Server.contrib.auth.middleware.AuthenticationMiddleware',
    'Server.contrib.messages.middleware.MessageMiddleware',
    'Server.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ppads_octogono.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ppads_octogono.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'Server.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'Server.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'Server.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'Server.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'Server.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'Server.db.models.BigAutoField'
