# Generated by Django 4.2.11 on 2024-03-30 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attendance_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendancerecord",
            name="attendance",
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="classMeta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="attendance_app.class"
            ),
        ),
    ]
