# Generated by Django 3.2.23 on 2024-03-31 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0002_remove_attendancerecord_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
