# Generated by Django 3.2.23 on 2024-03-31 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0003_attendancerecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='classMeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance_app.class'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('period', 'schoolGrade', 'classMeta', 'teacher')},
        ),
    ]
