# Generated by Django 3.2.8 on 2024-05-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0005_auto_20240515_1354'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='class',
            name='students',
        ),
        migrations.RemoveField(
            model_name='class',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='classMeta',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='classMeta',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='students',
        ),
    ]
